# url: https://y7kim.github.io
baseurl: /markosviggiato.github.io/
# access: http://127.0.0.1:4000/markosviggiato.github.io//

# Google Analytics
google_analytics: UA-174535928-1

gems: ["jemoji"]
gems:
  - jekyll-redirect-from
  
# Site settings
title: Markos Viggiato - Ph.D. Candidate | Natural Language Processing
email: markosviggiato@gmail.com
description: "This is the personal website for Markos Viggiato. Please contact me if you would like to talk about data analytics, machine learning and Artificial Intelligence application to games and software."


# Team names, titles and social links
people:
- name: Markos Viggiato
  pic: 1
  position: PhD Researcher
  social:
    - title: linkedin
      url: #
    - title: github
      url: #
    - title: twitter
      url: #


# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: https://www.linkedin.com/in/markosviggiato/
  - title: github
    url: https://github.com/markosviggiato
  - title: twitter
    url: https://twitter.com/viggiato

# Postal address (add as many lines as necessary)
address:
  - line: 9107 116 St NW
  - line: Edmonton, AB T6G 2V4

# Build settings
markdown: kramdown
permalink: pretty

